# Generated by Django 5.2.7 on 2025-10-31 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='rider',
            field=models.ForeignKey(db_column='rider_id', on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rideevent',
            name='ride',
            field=models.ForeignKey(db_column='ride_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rides.ride'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_time'], name='ride_pickup_time_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='ride_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_latitude', 'pickup_longitude'], name='ride_pickup_coords_idx'),
        ),
        migrations.AddIndex(
            model_name='rideevent',
            index=models.Index(fields=['ride', 'created_at'], name='ride_event_ride_created_idx'),
        ),
        migrations.AddIndex(
            model_name='rideevent',
            index=models.Index(fields=['created_at'], name='ride_event_created_idx'),
        ),
    ]
