# Generated by Django 5.2.7 on 2025-10-31 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="dropoff_latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="dropoff_longitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_longitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("en-route", "En Route to Pickup"),
                    ("pickup", "At Pickup"),
                    ("in-progress", "In Progress"),
                    ("dropoff", "At Dropoff"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                help_text="Ride status (e.g., 'en-route', 'pickup', 'dropoff')",
                max_length=50,
            ),
        ),
    ]
