# Generated by Django 5.2.7 on 2025-10-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),  # Depend on rides migration that creates the user table
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='User',
                    fields=[
                        ('id_user', models.AutoField(primary_key=True, serialize=False)),
                        ('role', models.CharField(help_text="User role (e.g., 'admin', 'rider', 'driver')", max_length=50)),
                        ('first_name', models.CharField(max_length=100)),
                        ('last_name', models.CharField(max_length=100)),
                        ('email', models.EmailField(max_length=255, unique=True)),
                        ('phone_number', models.CharField(max_length=20)),
                    ],
                    options={
                        'db_table': 'user',
                    },
                ),
            ],
            # Don't create the table in database since it already exists from rides migration
            database_operations=[],
        ),
    ]
